 /*
  * @(#)NBIeee1992PSS1AEditPanel.java   
  *
  * Copyright (C) 2006 www.interpss.org
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
  * as published by the Free Software Foundation; either version 2.1
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * @Author Mike Zhou
  * @Version 1.0
  * @Date 09/15/2006
  * 
  *   Revision History
  *   ================
  *
  */

package org.interpss.dstab.control.pss.bpa.si;

import java.util.Vector;

import org.interpss.dstab.control.base.EditHelper;
import org.interpss.ui.ICustomPluginEditor;

public class NBBpaSITypeStabilizerEditPanel extends javax.swing.JPanel implements ICustomPluginEditor {
	private static final long serialVersionUID = 1;

	// define data to be edited
	BpaSITypeStabilizerData _data;

    /** Creates new form FaultLocDataPanel */
    public NBBpaSITypeStabilizerEditPanel() {
        initComponents();
        // init the field to the default values
        _data = new BpaSITypeStabilizerData();
        setData2Editor("");
        
        // associate the editing fields with the verifier class defined at the end of this calss
  		DataVerifier verifier = new DataVerifier();
  	    ksTextField.setInputVerifier(verifier);
  	    t1TextField.setInputVerifier(verifier);
  	    t2TextField.setInputVerifier(verifier);
  	    t3TextField.setInputVerifier(verifier);
  	    t4TextField.setInputVerifier(verifier);
  	    t5TextField.setInputVerifier(verifier);
  	    t6TextField.setInputVerifier(verifier);
  	    vstmaxTextField.setInputVerifier(verifier);
  	    vstminTextField.setInputVerifier(verifier);
  	    k1TextField.setInputVerifier(verifier);
  	    a1TextField.setInputVerifier(verifier);
  	    a2TextField.setInputVerifier(verifier);
    }
    
    /**
     * Init the editor panel, which will be called from its parent editor
     */
	public void init(Object controller) {
		// init the data object from the bus object being edited
		_data = ((BPASITypeStabilizer)controller).getData();
	}
	
	/**
	*	Set controller data to the editor
	*
	* @return false if there is any problem
	*/
    public boolean setData2Editor(String desc) {
    	EditHelper.setDblTextFiled(ksTextField, 	_data.getKs(), "#0.00");
    	EditHelper.setDblTextFiled(t1TextField, 	_data.getT1(), "#0.000");
    	EditHelper.setDblTextFiled(t2TextField, 	_data.getT2(), "#0.000");
    	EditHelper.setDblTextFiled(t3TextField, 	_data.getT3(), "#0.000");
    	EditHelper.setDblTextFiled(t4TextField, 	_data.getT4(), "#0.000");
    	EditHelper.setDblTextFiled(t5TextField, 	_data.getT5(), "#0.000");
    	EditHelper.setDblTextFiled(t6TextField, 	_data.getT6(), "#0.000");
    	EditHelper.setDblTextFiled(vstmaxTextField, _data.getVsMax(), "#0.00");
    	EditHelper.setDblTextFiled(vstminTextField, _data.getVsMin(), "#0.000");
    	//TODO
//    	EditHelper.setDblTextFiled(k1TextField, 	_data.getKr(), "#0.000");
//    	EditHelper.setDblTextFiled(a1TextField, 	_data.getA1(), "#0.000");
//    	EditHelper.setDblTextFiled(a2TextField, 	_data.getA2(), "#0.000");

    	return true;
	}
    
	/**
	*	Save editor screen data to the controller data object
	*
	* @param errMsg error messages during the saving process.
	* @return false if there is any problem
	*/
    public boolean saveEditorData(Vector<String> errMsg) throws Exception {
    	errMsg.clear();
    	//TODO
//    	EditHelper.saveDblTextField(_data, ksTextField, "ks", errMsg);
//    	EditHelper.saveDblTextField(_data, t1TextField, "t1", errMsg);
//    	EditHelper.saveDblTextField(_data, t2TextField, "t2", errMsg);
//    	EditHelper.saveDblTextField(_data, t3TextField, "t3", errMsg);
//    	EditHelper.saveDblTextField(_data, t4TextField, "t4", errMsg);
//    	EditHelper.saveDblTextField(_data, t5TextField, "t5", errMsg);
//    	EditHelper.saveDblTextField(_data, t6TextField, "t6", errMsg);
//    	EditHelper.saveDblTextField(_data, vstmaxTextField, "vstmax", errMsg);
//    	EditHelper.saveDblTextField(_data, vstminTextField, "vstmin", errMsg);
//    	EditHelper.saveDblTextField(_data, k1TextField, "k1", errMsg);
//    	EditHelper.saveDblTextField(_data, a1TextField, "a1", errMsg);
//    	EditHelper.saveDblTextField(_data, a2TextField, "a2", errMsg);

    	return errMsg.size() == 0;
	}
    
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ksLabel = new javax.swing.JLabel();
        ksTextField = new javax.swing.JTextField();
        t1Label = new javax.swing.JLabel();
        t1TextField = new javax.swing.JTextField();
        t2Label = new javax.swing.JLabel();
        t2TextField = new javax.swing.JTextField();
        t3Label = new javax.swing.JLabel();
        t3TextField = new javax.swing.JTextField();
        t4Label = new javax.swing.JLabel();
        t4TextField = new javax.swing.JTextField();
        t5Label = new javax.swing.JLabel();
        t5TextField = new javax.swing.JTextField();
        t6Label = new javax.swing.JLabel();
        t6TextField = new javax.swing.JTextField();
        vstmaxLabel = new javax.swing.JLabel();
        vstmaxTextField = new javax.swing.JTextField();
        t8Label = new javax.swing.JLabel();
        vstminTextField = new javax.swing.JTextField();
        a1Label = new javax.swing.JLabel();
        a1TextField = new javax.swing.JTextField();
        a2Label = new javax.swing.JLabel();
        a2TextField = new javax.swing.JTextField();
        k1Label = new javax.swing.JLabel();
        k1TextField = new javax.swing.JTextField();

        ksLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        ksLabel.setText("Ks(pu)");

        ksTextField.setColumns(5);
        ksTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        ksTextField.setText("0.0");

        t1Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t1Label.setText("T1(s)");

        t1TextField.setColumns(5);
        t1TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t1TextField.setText("0.0");

        t2Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t2Label.setText("T2(s)");

        t2TextField.setColumns(5);
        t2TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t2TextField.setText("0.0");

        t3Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t3Label.setText("T3(s)");

        t3TextField.setColumns(5);
        t3TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t3TextField.setText("0.0");

        t4Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t4Label.setText("T4(s)");

        t4TextField.setColumns(5);
        t4TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t4TextField.setText("0.0");

        t5Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t5Label.setText("T5(s)");

        t5TextField.setColumns(5);
        t5TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t5TextField.setText("0.0");

        t6Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t6Label.setText("T6(s)");

        t6TextField.setColumns(5);
        t6TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t6TextField.setText("0.0");

        vstmaxLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        vstmaxLabel.setText("Vstmax(pu)");

        vstmaxTextField.setColumns(5);
        vstmaxTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        vstmaxTextField.setText("0.0");

        t8Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t8Label.setText("Vstmin(pu)");

        vstminTextField.setColumns(5);
        vstminTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        vstminTextField.setText("0.0");

        a1Label.setFont(new java.awt.Font("Dialog", 0, 12));
        a1Label.setText("A1");

        a1TextField.setColumns(5);
        a1TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        a1TextField.setText("0.0");

        a2Label.setFont(new java.awt.Font("Dialog", 0, 12));
        a2Label.setText("A2");

        a2TextField.setColumns(5);
        a2TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        a2TextField.setText("0.0");

        k1Label.setFont(new java.awt.Font("Dialog", 0, 12));
        k1Label.setText("K1");

        k1TextField.setColumns(5);
        k1TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        k1TextField.setText("0.0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(ksLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, t6Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, t3Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(layout.createSequentialGroup()
                        .add(k1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(k1TextField, 0, 0, Short.MAX_VALUE)
                    .add(t6TextField, 0, 0, Short.MAX_VALUE)
                    .add(t3TextField, 0, 0, Short.MAX_VALUE)
                    .add(ksTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .add(55, 55, 55)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, t1Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(t4Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(vstmaxLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(a1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(a1TextField, 0, 0, Short.MAX_VALUE)
                    .add(vstmaxTextField, 0, 0, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(t4TextField, 0, 0, Short.MAX_VALUE))
                    .add(t1TextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .add(42, 42, 42)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(a2Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .add(t5Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .add(t2Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, t8Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(a2TextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, t2TextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .add(t5TextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .add(vstminTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .add(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(t2TextField)
                            .add(t2Label))
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(t5TextField)
                            .add(t5Label))
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(vstminTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t8Label)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(t1TextField)
                                .add(t1Label))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(ksTextField)
                                .add(ksLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(t4TextField)
                            .add(t3TextField)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(t3Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(t4Label)))
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(vstmaxTextField)
                            .add(t6TextField)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(t6Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(vstmaxLabel)))
                        .add(14, 14, 14)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(a2Label)
                            .add(a2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(a1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(a1Label)
                            .add(k1Label)
                            .add(k1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1Label;
    private javax.swing.JTextField a1TextField;
    private javax.swing.JLabel a2Label;
    private javax.swing.JTextField a2TextField;
    private javax.swing.JLabel k1Label;
    private javax.swing.JTextField k1TextField;
    private javax.swing.JLabel ksLabel;
    private javax.swing.JTextField ksTextField;
    private javax.swing.JLabel t1Label;
    private javax.swing.JTextField t1TextField;
    private javax.swing.JLabel t2Label;
    private javax.swing.JTextField t2TextField;
    private javax.swing.JLabel t3Label;
    private javax.swing.JTextField t3TextField;
    private javax.swing.JLabel t4Label;
    private javax.swing.JTextField t4TextField;
    private javax.swing.JLabel t5Label;
    private javax.swing.JTextField t5TextField;
    private javax.swing.JLabel t6Label;
    private javax.swing.JTextField t6TextField;
    private javax.swing.JLabel t8Label;
    private javax.swing.JLabel vstmaxLabel;
    private javax.swing.JTextField vstmaxTextField;
    private javax.swing.JTextField vstminTextField;
    // End of variables declaration//GEN-END:variables

    // define data validation rules
	class DataVerifier extends javax.swing.InputVerifier {
    	@Override
		public boolean verify(javax.swing.JComponent input) {
			if (input == null)
				return false;
       		try {
       			// data field verification rules
//    			if ( input == ksTextField)
//    				return EditHelper.checkDblDataRange(input, _data, "ks");
//    			if ( input == k1TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "k1");
//    			if ( input == t1TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "t1");
//    			if ( input == t2TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "t2");
//    			if ( input == t3TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "t3");
//    			if ( input == t4TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "t4");
//    			if ( input == t5TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "t5");
//    			if ( input == t6TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "t6");
//    			if ( input == vstmaxTextField)
//    				return EditHelper.checkDblDataRange(input, _data, "vstmax");
//    			if ( input == vstminTextField)
//    				return EditHelper.checkDblDataRange(input, _data, "vstmin");
//    			if ( input == a1TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "a1");
//    			if ( input == a2TextField)
//    				return EditHelper.checkDblDataRange(input, _data, "a2");
 	       	} catch (Exception e) {
 	    		return false;
 	       	}		
			return true;
        }
    }
}
