#!/usr/bin/env python3
"""Generate the ANDES CPF reference for the shared WECC179 v32 fixture."""

import argparse
import hashlib
from pathlib import Path

import andes


FIXTURE_SHA256 = "623ba186fc317abd3e61be456129bebfe8b1512819307e91b659ea7a299baad3"
LOAD_SCALE = 2.0
TARGET_LAMBDAS = (0.02, 0.06, 0.10, 0.115)
ANDES_COMMIT = "eda5163c9ee8d19945a1dd5d1771fec5da608c27"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "raw",
        nargs="?",
        type=Path,
        default=Path(__file__).with_name("wecc_179_v32.raw"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("andes_cpf_reference.properties"),
    )
    args = parser.parse_args()

    fixture_hash = hashlib.sha256(args.raw.read_bytes()).hexdigest()
    if fixture_hash != FIXTURE_SHA256:
        raise SystemExit(
            f"fixture SHA-256 mismatch: expected {FIXTURE_SHA256}, got {fixture_hash}"
        )

    system = andes.load(str(args.raw), default_config=True, no_output=True)
    if system is None or not system.PFlow.run():
        raise SystemExit("ANDES power flow did not converge")

    buses = tuple(int(bus) for bus in system.Bus.idx.v)
    base_voltages = {
        bus: float(system.Bus.v.v[system.Bus.idx2uid(bus)]) for bus in buses
    }
    target_voltages = {}
    point_counts = {}
    for target_lambda in TARGET_LAMBDAS:
        system.CPF.config.stop_at = target_lambda
        if not system.CPF.run(load_scale=LOAD_SCALE):
            raise SystemExit(f"ANDES CPF did not converge at lambda={target_lambda}")
        if abs(float(system.CPF.lam[-1]) - target_lambda) > 1.0e-9:
            raise SystemExit(f"ANDES CPF stopped at lambda={system.CPF.lam[-1]}")
        point_counts[target_lambda] = len(system.CPF.lam)
        target_voltages[target_lambda] = {
            bus: float(system.CPF.V[system.Bus.idx2uid(bus), -1]) for bus in buses
        }

    for bus, base_voltage in base_voltages.items():
        restored = float(system.Bus.v.v[system.Bus.idx2uid(bus)])
        if abs(restored - base_voltage) > 1.0e-12:
            raise SystemExit(f"ANDES did not restore bus {bus}: {restored}")

    lines = [
        "# Generated by andes_cpf_reference.py from the exact pinned RAW fixture.",
        f"fixture.sha256={fixture_hash}",
        f"andes.version={andes.__version__}",
        f"andes.commit={ANDES_COMMIT}",
        "andes.invocation=CPF.run(load_scale=2.0) with config.stop_at per target",
        f"load.scale={LOAD_SCALE}",
        "target.lambdas=" + ",".join(f"{value:.3f}" for value in TARGET_LAMBDAS),
        "comparison.buses=" + ",".join(str(bus) for bus in buses),
    ]
    for bus in buses:
        lines.append(f"bus.{bus}.baseVoltage={base_voltages[bus]:.12f}")
    for target_lambda in TARGET_LAMBDAS:
        key = f"{target_lambda:.3f}"
        lines.append(f"point.{key}.andes.pointCount={point_counts[target_lambda]}")
        for bus in buses:
            lines.append(
                f"point.{key}.bus.{bus}.voltage="
                f"{target_voltages[target_lambda][bus]:.12f}"
            )
    args.output.write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.output} with {len(buses)} buses and {len(TARGET_LAMBDAS)} points")


if __name__ == "__main__":
    main()
